# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from showproducts import Ui_Dialog
from stockwindow2 import Ui_StockWindow
from modifyproducts2 import Ui_ModifyWindow
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 575)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setAutoFillBackground(False)
        #self.centralwidget.setStyleSheet("background-color: rgb(250, 128, 114)")
        self.centralwidget.setStyleSheet("background-color: rgb(251, 193, 193)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(239, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.bar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Z003 [urw]")
        font.setPointSize(70)
        self.bar.setFont(font)
        self.bar.setScaledContents(True)
        self.bar.setObjectName("bar")
        self.horizontalLayout_4.addWidget(self.bar)
        spacerItem1 = QtWidgets.QSpacerItem(289, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(17, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.searchbar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchbar.setMinimumSize(QtCore.QSize(600, 70))
        self.searchbar.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.searchbar.setFont(font)
        self.searchbar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.searchbar.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-width : 1.2px;\n"
"border-style:inset;\n"
"background-color: rgb(255, 255, 255)")
        self.searchbar.setObjectName("searchbar")
        self.horizontalLayout_3.addWidget(self.searchbar)
        self.searchbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchbutton.sizePolicy().hasHeightForWidth())
        self.searchbutton.setSizePolicy(sizePolicy)
        self.searchbutton.setMinimumSize(QtCore.QSize(150, 70))
        self.searchbutton.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.searchbutton.setFont(font)
        self.searchbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchbutton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-width : 1.2px;\n"
"border-style:inset;\n"
"background-color: rgb(255, 255, 255)\n"
"")
        self.searchbutton.setObjectName("searchbutton")
        self.horizontalLayout_3.addWidget(self.searchbutton)
        spacerItem5 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(17, 83, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(17, 83, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(86, 75, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.stockbutton = QtWidgets.QPushButton(self.centralwidget)
        self.stockbutton.setMinimumSize(QtCore.QSize(229, 90))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.stockbutton.setFont(font)
        self.stockbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stockbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stockbutton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-width : 1.2px;\n"
"border-style:inset;\n"
"background-color: rgb(255, 255, 255)")
        self.stockbutton.setCheckable(False)
        self.stockbutton.setObjectName("stockbutton")
        self.horizontalLayout.addWidget(self.stockbutton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.modify = QtWidgets.QPushButton(self.centralwidget)
        self.modify.setMinimumSize(QtCore.QSize(229, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.modify.setFont(font)
        self.modify.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modify.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-width : 1.2px;\n"
"border-style:inset;\n"
"background-color: rgb(255, 255, 255)")
        self.modify.setObjectName("modify")
        self.horizontalLayout.addWidget(self.modify)
        spacerItem10 = QtWidgets.QSpacerItem(85, 75, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(14, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(14, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Activation for searchbutton
        self.searchbutton.clicked.connect(self.searchbutton_clicked)

        # Activation for stockbutton
        self.stockbutton.clicked.connect(self.stockbutton_clicked)

        # Activation for modify
        self.modify.clicked.connect(self.modifybutton_clicked)


    def searchbutton_clicked(self):
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog(self.searchbar.text(), Dialog)
        ui.setupUi(Dialog)
        Dialog.show()

        #MainWindow.hide()
        Dialog.exec_()
        #MainWindow.show()

    def stockbutton_clicked(self):
        self.StockWindow = QtWidgets.QMainWindow()
        self.ui = Ui_StockWindow()
        self.ui.setupUi(self.StockWindow)
        self.StockWindow.show()

    def modifybutton_clicked(self):
        self.ModifyWindow = QtWidgets.QMainWindow()
        self.ui = Ui_ModifyWindow()
        self.ui.setupUi(self.ModifyWindow)
        self.ModifyWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bar.setText(_translate("MainWindow", "Lenceria Sophia"))
        self.searchbutton.setText(_translate("MainWindow", "Buscar"))
        self.stockbutton.setText(_translate("MainWindow", "Ver Stock"))
        self.modify.setText(_translate("MainWindow", "Modificar Precios"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)

    def closeEvent(self, event):
        # Ask for confirmation
        answer = QtWidgets.QMessageBox.question(self,
        "Salir..",
        "Esta seguro que quiere salir?\nSe perdera la informacion no guardada.",
        QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        if answer == QtWidgets.QMessageBox.Yes:
            app.quit()
        else:
            event.ignore()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
#    MainWindow = QtWidgets.QMainWindow()
#    MainWindow.setQuitOnLastWindowClosed(True)
    MainWindow = MainWindow()
#    ui = Ui_MainWindow()
#    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



#from PyQt5.QtWidgets import QTableWidgetItem
#from db_handler import *


#    def __init__(self, value, Dialog):
#        self.value = value
#        self.Dialog = Dialog
#        self.send_data_to_table()


#        self.Cerrar.clicked.connect(self.reject)
#
#    def reject(self):
#        self.Dialog.close()

#        self.tableWidget.setStyleSheet("background: url(./imagenes/sophia.png);\n"
#"background-repeat: no-repeat;\n"
#"background-position: center")

#    def send_data_to_table(self):
#        product = show_product(self.value)
#        print(product)
#        self.tableWidget.setRowCount(0)
#        for row_number, row_data, in enumerate(product):
#            print(row_number)
#            self.tableWidget.insertRow(row_number)
#            for column_number, data in enumerate(row_data):
#                self.tableWidget.setItem(row_number,column_number,
#                    QTableWidgetItem(str(data)))

#