# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifyproducts2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from db_handler import *


class Ui_ModifyWindow(object):
    def __init__(self):
        self.row_count = 0
        self.barcode_list = []
        self.add_prod_row_count = 0

    def setupUi(self, ModifyWindow):
        ModifyWindow.setObjectName("ModifyWindow")
        ModifyWindow.resize(1195, 750)
        ModifyWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ModifyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgba(251, 193, 193, 158);")
        self.tabWidget.setObjectName("tabWidget")
        self.from_file = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(16)
        self.from_file.setFont(font)
        self.from_file.setObjectName("from_file")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.from_file)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_bar = QtWidgets.QLineEdit(self.from_file)
        self.file_bar.setMinimumSize(QtCore.QSize(0, 70))
        self.file_bar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.file_bar.setObjectName("file_bar")
        self.horizontalLayout.addWidget(self.file_bar)
        self.browse = QtWidgets.QPushButton(self.from_file)
        self.browse.setMinimumSize(QtCore.QSize(120, 70))
        self.browse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.browse.setObjectName("browse")
        self.horizontalLayout.addWidget(self.browse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.radioLoad = QtWidgets.QRadioButton(self.from_file)
        self.radioLoad.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.radioLoad.setFont(font)
        self.radioLoad.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
 "color: rgb(0, 0, 0 )")
        self.radioLoad.setStyleSheet("QRadioButton::checked:pressed"
                                        "{"
                                        "background-color :rgba(255, 255, 255, 0)"
                                        "}")
        self.horizontalLayout_2.addWidget(self.radioLoad)
        spacerItem1 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.radiomodify = QtWidgets.QRadioButton(self.from_file)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radiomodify.setFont(font)
        self.radiomodify.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
 "color: rgb(0, 0, 0 )")
        self.radiomodify.setStyleSheet("QRadioButton::checked:pressed"
                                        "{"
                                        "background-color :rgba(255, 255, 255, 0)"
                                        "}")
        self.radiomodify.setObjectName("radiomodify")
        self.horizontalLayout_2.addWidget(self.radiomodify)
        spacerItem2 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.radioDelete = QtWidgets.QRadioButton(self.from_file)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioDelete.setFont(font)
        self.radioDelete.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
 "color: rgb(0, 0, 0 )")
        self.radioDelete.setStyleSheet("QRadioButton::checked:pressed"
                                        "{"
                                        "background-color :rgba(255, 255, 255, 0)"
                                        "}")
        self.radioDelete.setObjectName("radioDelete")
        self.horizontalLayout_2.addWidget(self.radioDelete)
        spacerItem3 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.load_delete_modify = QtWidgets.QPushButton(self.from_file)
        self.load_delete_modify.setMinimumSize(QtCore.QSize(0, 70))
        self.load_delete_modify.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.load_delete_modify.setObjectName("load_delete_modify")
        self.verticalLayout.addWidget(self.load_delete_modify)
        self.progressBar = QtWidgets.QProgressBar(self.from_file)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 50))
        self.progressBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.listWidget_load_modify_delete = QtWidgets.QListWidget(self.from_file)
        self.listWidget_load_modify_delete.setMinimumSize(QtCore.QSize(50, 40))
        self.listWidget_load_modify_delete.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget_load_modify_delete.setObjectName("listWidget_load_modify_delete")
        self.verticalLayout.addWidget(self.listWidget_load_modify_delete)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.from_file, "")
        self.Add_prod = QtWidgets.QWidget()
        self.Add_prod.setObjectName("Add_prod")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Add_prod)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget_product_added = QtWidgets.QTableWidget(self.Add_prod)
        self.tableWidget_product_added.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_product_added.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_product_added.setObjectName("tableWidget_product_added")
        self.tableWidget_product_added.setColumnCount(5)
        self.tableWidget_product_added.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_product_added.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_product_added.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_product_added.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_product_added.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_product_added.setHorizontalHeaderItem(4, item)
        self.tableWidget_product_added.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_product_added.horizontalHeader().setDefaultSectionSize(159)
        self.tableWidget_product_added.horizontalHeader().setMinimumSectionSize(159)
        self.tableWidget_product_added.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget_product_added.horizontalHeader().setSectionResizeMode(0,QHeaderView.Stretch)
        self.tableWidget_product_added.horizontalHeader().setSectionResizeMode(1,QHeaderView.Stretch)
        self.tableWidget_product_added.horizontalHeader().setSectionResizeMode(2,QHeaderView.Stretch)
        self.tableWidget_product_added.horizontalHeader().setSectionResizeMode(3,QHeaderView.Stretch)
        self.tableWidget_product_added.horizontalHeader().setSectionResizeMode(4,QHeaderView.Stretch)
        self.tableWidget_product_added.setStyleSheet("background-image: url(./imagenes/sophia_trans.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-color:rgb(255, 255, 255)")
        self.tableWidget_product_added.horizontalHeader().setStyleSheet("background-color: rgb(255,255,255)")
        self.tableWidget_product_added.verticalHeader().setStyleSheet("background-image: url(./imagenes/headerv.png)")

        self.horizontalLayout_9.addWidget(self.tableWidget_product_added)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.name = QtWidgets.QLineEdit(self.Add_prod)
        self.name.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Chilanka")
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setPlaceholderText("Nombre")
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.name)
        self.stored_stock = QtWidgets.QLineEdit(self.Add_prod)
        self.stored_stock.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Chilanka")
        self.stored_stock.setFont(font)
        self.stored_stock.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stored_stock.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.stored_stock.setText("")
        self.stored_stock.setAlignment(QtCore.Qt.AlignCenter)
        self.stored_stock.setObjectName("stored_stock")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.stored_stock)
        self.front_stock = QtWidgets.QLineEdit(self.Add_prod)
        self.front_stock.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Chilanka")
        self.front_stock.setFont(font)
        self.front_stock.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.front_stock.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.front_stock.setAlignment(QtCore.Qt.AlignCenter)
        self.front_stock.setObjectName("front_stock")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.front_stock)
        self.price = QtWidgets.QLineEdit(self.Add_prod)
        self.price.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Chilanka")
        self.price.setFont(font)
        self.price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.price.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.price.setAlignment(QtCore.Qt.AlignCenter)
        self.price.setObjectName("price")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.price)
        self.barcode = QtWidgets.QLineEdit(self.Add_prod)
        self.barcode.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Chilanka")
        self.barcode.setFont(font)
        self.barcode.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.barcode.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.barcode.setAlignment(QtCore.Qt.AlignCenter)
        self.barcode.setObjectName("barcode")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.barcode)
        self.save_button = QtWidgets.QPushButton(self.Add_prod)
        self.save_button.setEnabled(True)
        self.save_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.save_button.setFont(font)
        self.save_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_button.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.save_button.setCheckable(False)
        self.save_button.setObjectName("save_button")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.save_button)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_10.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.Add_prod, "")
        self.modify_product = QtWidgets.QWidget()
        self.modify_product.setObjectName("modify_product")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.modify_product)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchbar_modify = QtWidgets.QLineEdit(self.modify_product)
        self.searchbar_modify.setMinimumSize(QtCore.QSize(0, 70))
        self.searchbar_modify.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchbar_modify.setAlignment(QtCore.Qt.AlignCenter)
        self.searchbar_modify.setObjectName("searchbar_modify")
        self.horizontalLayout_3.addWidget(self.searchbar_modify)
        self.searchbutton_modify = QtWidgets.QPushButton(self.modify_product)
        self.searchbutton_modify.setMinimumSize(QtCore.QSize(120, 70))
        self.searchbutton_modify.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchbutton_modify.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.searchbutton_modify.setObjectName("searchbutton_modify")
        self.horizontalLayout_3.addWidget(self.searchbutton_modify)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 112, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.name_modify = QtWidgets.QLineEdit(self.modify_product)
        self.name_modify.setMinimumSize(QtCore.QSize(0, 50))
        self.name_modify.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_modify.setAlignment(QtCore.Qt.AlignCenter)
        self.name_modify.setPlaceholderText("Nombre")
        self.name_modify.setObjectName("name_modify")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.name_modify)
        self.stored_stock_modify = QtWidgets.QLineEdit(self.modify_product)
        self.stored_stock_modify.setMinimumSize(QtCore.QSize(0, 50))
        self.stored_stock_modify.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stored_stock_modify.setText("")
        self.stored_stock_modify.setAlignment(QtCore.Qt.AlignCenter)
        self.stored_stock_modify.setObjectName("stored_stock_modify")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.stored_stock_modify)
        self.front_stock_modify = QtWidgets.QLineEdit(self.modify_product)
        self.front_stock_modify.setMinimumSize(QtCore.QSize(0, 50))
        self.front_stock_modify.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.front_stock_modify.setAlignment(QtCore.Qt.AlignCenter)
        self.front_stock_modify.setObjectName("front_stock_modify")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.front_stock_modify)
        self.price_modify = QtWidgets.QLineEdit(self.modify_product)
        self.price_modify.setMinimumSize(QtCore.QSize(0, 50))
        self.price_modify.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.price_modify.setAlignment(QtCore.Qt.AlignCenter)
        self.price_modify.setObjectName("price_modify")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.price_modify)
        self.barcode_modify = QtWidgets.QLineEdit(self.modify_product)
        self.barcode_modify.setMinimumSize(QtCore.QSize(0, 50))
        self.barcode_modify.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.barcode_modify.setAlignment(QtCore.Qt.AlignCenter)
        self.barcode_modify.setObjectName("barcode_modify")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.barcode_modify)
        self.load_button_modify = QtWidgets.QPushButton(self.modify_product)
        self.load_button_modify.setMinimumSize(QtCore.QSize(0, 50))
        self.load_button_modify.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_button_modify.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.load_button_modify.setObjectName("load_button_modify")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.load_button_modify)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.tabWidget.addTab(self.modify_product, "")
        self.delete_product = QtWidgets.QWidget()
        self.delete_product.setObjectName("delete_product")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.delete_product)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchbar_delete = QtWidgets.QLineEdit(self.delete_product)
        self.searchbar_delete.setMinimumSize(QtCore.QSize(0, 70))
        self.searchbar_delete.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchbar_delete.setAlignment(QtCore.Qt.AlignCenter)
        self.searchbar_delete.setObjectName("searchbar_delete")
        self.horizontalLayout_4.addWidget(self.searchbar_delete)
        self.searchbutton_delete = QtWidgets.QPushButton(self.delete_product)
        self.searchbutton_delete.setMinimumSize(QtCore.QSize(120, 70))
        self.searchbutton_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchbutton_delete.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.searchbutton_delete.setObjectName("searchbutton_delete")
        self.horizontalLayout_4.addWidget(self.searchbutton_delete)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.tableWidget_delete = QtWidgets.QTableWidget(self.delete_product)
        self.tableWidget_delete.setMinimumSize(QtCore.QSize(0, 450))
        self.tableWidget_delete.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_delete.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_delete.setObjectName("tableWidget_delete")
        self.tableWidget_delete.setColumnCount(3)
        self.tableWidget_delete.setRowCount(0)
        self.tableWidget_delete.horizontalHeader().setSectionResizeMode(0,QHeaderView.Stretch)
        self.tableWidget_delete.horizontalHeader().setSectionResizeMode(1,QHeaderView.Stretch)
        self.tableWidget_delete.horizontalHeader().setSectionResizeMode(2,QHeaderView.Stretch)
        self.tableWidget_delete.setStyleSheet("background-image: url(./imagenes/sophia_trans.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-color:rgb(255, 255, 255)")
        self.tableWidget_delete.horizontalHeader().setStyleSheet("background-color: rgb(255,255,255)")
        self.tableWidget_delete.verticalHeader().setStyleSheet("background-image: url(./imagenes/headerv.png)")

        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_delete.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_delete.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_delete.setHorizontalHeaderItem(2, item)
        self.tableWidget_delete.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_delete.horizontalHeader().setMinimumSectionSize(80)
        self.verticalLayout_3.addWidget(self.tableWidget_delete)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem12 = QtWidgets.QSpacerItem(298, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.deletebutton = QtWidgets.QPushButton(self.delete_product)
        self.deletebutton.setMinimumSize(QtCore.QSize(500, 60))
        self.deletebutton.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.deletebutton.setObjectName("deletebutton")
        self.horizontalLayout_7.addWidget(self.deletebutton)
        spacerItem13 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.delete_product, "")
        self.horizontalLayout_8.addWidget(self.tabWidget)
        ModifyWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ModifyWindow)
        self.statusbar.setObjectName("statusbar")
        ModifyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ModifyWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(ModifyWindow)

    def retranslateUi(self, ModifyWindow):
        _translate = QtCore.QCoreApplication.translate
        ModifyWindow.setWindowTitle(_translate("ModifyWindow", "MainWindow"))
        self.browse.setText(_translate("ModifyWindow", "Buscar archivo"))
        self.radioLoad.setText(_translate("ModifyWindow", "Cargar"))
        self.radiomodify.setText(_translate("ModifyWindow", "Modificar"))
        self.radioDelete.setText(_translate("ModifyWindow", "Eliminar"))
        self.load_delete_modify.setText(_translate("ModifyWindow", "Cargar, Modificar o Eliminar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.from_file), _translate("ModifyWindow", "Modificar por un archivo"))
        item = self.tableWidget_product_added.horizontalHeaderItem(0)
        item.setText(_translate("ModifyWindow", "Nombre"))
        item = self.tableWidget_product_added.horizontalHeaderItem(1)
        item.setText(_translate("ModifyWindow", "Precio"))
        item = self.tableWidget_product_added.horizontalHeaderItem(2)
        item.setText(_translate("ModifyWindow", "Stock en deposito"))
        item = self.tableWidget_product_added.horizontalHeaderItem(3)
        item.setText(_translate("ModifyWindow", "Stock en mostrador"))
        item = self.tableWidget_product_added.horizontalHeaderItem(4)
        item.setText(_translate("ModifyWindow", "Codigo de barras"))
        self.stored_stock.setPlaceholderText(_translate("ModifyWindow", "Stock en el deposito"))
        self.front_stock.setPlaceholderText(_translate("ModifyWindow", "Stock en el mostrador"))
        self.price.setPlaceholderText(_translate("ModifyWindow", "Precio"))
        self.barcode.setPlaceholderText(_translate("ModifyWindow", "Codigo de barras"))
        self.save_button.setText(_translate("ModifyWindow", "Cargar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Add_prod), _translate("ModifyWindow", "Agregar producto"))
        self.searchbar_modify.setPlaceholderText(_translate("ModifyWindow", "Nombre del producto"))
        self.searchbutton_modify.setText(_translate("ModifyWindow", "Buscar"))
        self.stored_stock_modify.setPlaceholderText(_translate("ModifyWindow", "Stock en el deposito"))
        self.front_stock_modify.setPlaceholderText(_translate("ModifyWindow", "Stock en el mostrador"))
        self.price_modify.setPlaceholderText(_translate("ModifyWindow", "Precio"))
        self.barcode_modify.setPlaceholderText(_translate("ModifyWindow", "Codigo de barras"))
        self.load_button_modify.setText(_translate("ModifyWindow", " Modificar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.modify_product), _translate("ModifyWindow", "Modificar producto"))
        self.searchbar_delete.setPlaceholderText(_translate("ModifyWindow", "Nombre del producto"))
        self.searchbutton_delete.setText(_translate("ModifyWindow", "Buscar"))
        item = self.tableWidget_delete.horizontalHeaderItem(0)
        item.setText(_translate("ModifyWindow", "Nombre"))
        item = self.tableWidget_delete.horizontalHeaderItem(1)
        item.setText(_translate("ModifyWindow", "Codigo de barras"))
        item = self.tableWidget_delete.horizontalHeaderItem(2)
        item.setText(_translate("ModifyWindow", "Eliminar"))
        self.deletebutton.setText(_translate("ModifyWindow", "Eliminar seleccionados"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.delete_product), _translate("ModifyWindow", "Eliminar_producto"))

        self.validate_int()
        self.validate_string()
        self.validate_barcode()

        # Activation for save_button in add_prod.
        self.save_button.clicked.connect(self.save_button_clicked)

        # Activation for searchbutton_modify
        self.searchbutton_modify.clicked.connect(self.searchbutton_modify_clicked)

        #Save modifications button. (Wrong name)
        self.load_button_modify.clicked.connect(self.load_button_modify_clicked)

        # Activation for searchbutton_delete
        self.searchbutton_delete.clicked.connect(self.searchbutton_delete_clicked)

        # Activation deletebutton
        self.deletebutton.clicked.connect(self.deletebutton_clicked)



# Funtions Handlers

    def get_checked_products(self):
        if self.row_count == 0:
           return(0)
        else:
            for i in range(self.row_count):
                if self.tableWidget_delete.item(i,2).checkState() == Qt.Checked:
                    self.barcode_list.append(int(self.tableWidget_delete.item(i,1).text()))
                    

    def validate_int(self):
        regex = QRegExp(r'[0-9]+')
        int_validator = QRegExpValidator(regex)
        self.barcode.setValidator(int_validator)
        self.price.setValidator(int_validator)
        self.stored_stock.setValidator(int_validator)
        self.front_stock.setValidator(int_validator)
        self.price_modify.setValidator(int_validator)
        self.front_stock_modify.setValidator(int_validator)
        self.stored_stock_modify.setValidator(int_validator)
        self.barcode_modify.setValidator(int_validator)

    def validate_barcode(self):
        regex = QRegExp(r'[0-9.]+')
        int_validator = QRegExpValidator(regex)
        self.searchbar_modify.setValidator(int_validator)

    def converte_validation_for_modify(self):
        regex = QRegExp("^[a-zA-Z0-9_.-, ]*$")
        str_validator = QRegExpValidator(regex)
        self.name_modify.setValidator(str_validator)
        self.price_modify.setValidator(str_validator)
        self.front_stock_modify.setValidator(str_validator)
        self.stored_stock_modify.setValidator(str_validator)
        self.barcode_modify.setValidator(str_validator)


    #Prevent user to inser numbers in
    def validate_string(self):
        regex = QRegExp("^[a-zA-Z0-9_.-, ]*$")
        str_validator = QRegExpValidator(regex)
        self.name.setValidator(str_validator)
        self.name_modify.setValidator(str_validator)


    #Empty Qlines in front end
    # Method = 0, for Qlines in modification tab
    # Method = 1, for Qlines in add tab
    def empty_Qline(self,method):
        if(method == 0):
            self.name_modify.clear()
            self.front_stock_modify.clear()
            self.stored_stock_modify.clear()
            self.price_modify.clear()
            self.barcode_modify.clear()
            self.searchbar_modify.clear()
        else:
            self.name.clear()
            self.price.clear()
            self.front_stock.clear()
            self.stored_stock.clear()
            self.barcode.clear()
    

    def send_search_to_QLineEdit(self,value):
        self.converte_validation_for_modify()
        self.name_modify.insert(str(value[0][0]))
        self.price_modify.insert(str(int(value[0][1])))
        self.front_stock_modify.insert(str(int(value[0][2])))
        self.stored_stock_modify.insert(str(int(value[0][3])))
        self.barcode_modify.insert(str(int(value[0][4])))
        self.validate_int()

    #Check QLines from modify and add product not empty when trying to save changes
    def add_QLineEdit_not_empty(self):
        if (self.name.text() != "" and self.stored_stock.text() != "" and
            self.front_stock.text() != "" and self.price.text() != "" and
            self.barcode.text() != ""):
            return(True)

    def modify_QLineEdit_not_empty(self):
        if (self.name_modify.text() != "" and self.stored_stock_modify.text() != "" and
            self.front_stock_modify.text() != "" and self.price_modify.text() != "" and
            self.barcode_modify.text() != ""):
            return(True)

#----------------------------------------------------------------------------------------------------------

# button Conectors:


    def save_button_clicked(self):
        if(self.add_QLineEdit_not_empty() != True):
            return(0)
        column_index = 0
        self.tableWidget_product_added.insertRow(self.add_prod_row_count)
        data_array = [self.name.text(), self.front_stock.text(), self.stored_stock.text(),
                    self.price.text(), self.barcode.text()]

        added = add_prod(self.name.text(), self.front_stock.text(), self.stored_stock.text(),
                    self.price.text(), self.barcode.text())
       
        if(added):
            for data in data_array:
                if type(data) == float:
                    data = int(data)
                item = QTableWidgetItem(str(data))
                item.setTextAlignment(Qt.AlignCenter)
                font = QtGui.QFont()
                font.setPointSize(18)
                item.setFont(font)
                self.tableWidget_product_added.setItem(self.add_prod_row_count,column_index,item)
                column_index = column_index + 1
            self.add_prod_row_count = self.add_prod_row_count + 1
        self.add_prod_row_count = self.add_prod_row_count + 1
        self.empty_Qline(1)


    def searchbutton_modify_clicked(self):
        if self.searchbar_modify.text() == "":
            return(0)      
        product = get_full_product(self.searchbar_modify.text())
        if product == []:
            return(0)
        self.send_search_to_QLineEdit(product)
        #update_product(self.name_modify.text(), self.front_stock_modify.text(), self.stored_stock.text(),
        #            self.price.text(), self.barcode.text())
        #self.empty_Qline(0)

    def load_button_modify_clicked(self):
        if(self.modify_QLineEdit_not_empty() != True):
            return(0)
        update_product(self.name_modify.text(),self.price_modify.text(), self.front_stock_modify.text(),
                            self.stored_stock_modify.text(), self.barcode_modify.text())
        self.empty_Qline(0)


    def searchbutton_delete_clicked(self):
        #self.tableWidget_delete.clearContents()
        product = show_products_delete(self.searchbar_delete.text())
        self.row_count = 0
        self.tableWidget_delete.setRowCount(0)
        for row_number, row_data, in enumerate(product):
            self.row_count = self.row_count + 1 
            self.tableWidget_delete.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                if type(data) == float:
                    data = int(data)
                item = QTableWidgetItem(str(data))
                item.setTextAlignment(Qt.AlignCenter)
                font = QtGui.QFont()
                font.setPointSize(18)
                item.setFont(font)
                self.tableWidget_delete.setItem(row_number,column_number,item)
            #Create CheckBox 
            check_box_item = QTableWidgetItem()
#            if input_bool== True:
#                check_box_item.setCheckState(Qt.Checked)
#            else:    
            check_box_item.setCheckState(Qt.Unchecked)
            check_box_item.setText("Seleccionar")
            #check_box_item.setTextAlignment(Qt.AlignLeft)
            # Add CheckBox in the last column in every row
            font = QtGui.QFont()
            font.setPointSize(18)
            check_box_item.setFont(font)
            self.tableWidget_delete.setItem(row_number,2,check_box_item)
#        self.tableWidget_delete.resizeColumnsToContents()


    def deletebutton_clicked(self,input_value):
#        delete_product("totora")
        products = self.get_checked_products()
        for item in self.barcode_list:
            print(item)
            delete_product(item)
        self.searchbutton_delete_clicked()
        self.barcode_list = []

#-----------------------------------------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModifyWindow = QtWidgets.QMainWindow()
    ui = Ui_ModifyWindow()
    ui.setupUi(ModifyWindow)
    ModifyWindow.show()
    sys.exit(app.exec_())
