# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saleswindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from db_handler import *
from saleswindow import Ui_SalesWindow
from datetime import date as dt

class SalesWindow(QtWidgets.QMainWindow, Ui_SalesWindow):
    def __init__(self, *args, obj=None, **kwargs):
        super(SalesWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)
        self.date_value = QLineEdit()



        # Activation for close_button
        self.close_button.clicked.connect(self.close_button_clicked)

        self.show_sales.clicked.connect(self.show_sales_clicked)

    def show_sales_clicked(self):
        from_date= self.date_from.date().toString("yyyy-MM-dd")
        to_date = self.date_to.date().toString("yyyy-MM-dd")
        sales = get_sales(from_date, to_date)
        self.tableWidget.setRowCount(0)
        for row_number, row_data, in enumerate(sales):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                if column_number == 4:
                    data = QDate.fromString(data, 'yyyy-MM-dd')
                    data = data.toString('dd-MM-yyyy')
                item = QTableWidgetItem(str(data))
                item.setTextAlignment(Qt.AlignCenter)
                font = QtGui.QFont()
                font.setPointSize(18)
                item.setFont(font)
                self.tableWidget.setItem(row_number,column_number,item)
        #self.tableWidget.resizeColumnsToContents()


    def close_button_clicked(self):
        self.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SalesWindow  = SalesWindow()
    SalesWindow.show()
    sys.exit(app.exec_())



