# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stockwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QHeaderView
from PyQt5.QtCore import Qt
from db_handler import *


class Ui_StockWindow(object):
    def __init__(self):
        self.row_count = 0
        self.checked_list = []

    def setupUi(self, StockWindow):
        StockWindow.setObjectName("StockWindow")
        StockWindow.resize(1300, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StockWindow.sizePolicy().hasHeightForWidth())
        StockWindow.setSizePolicy(sizePolicy)
        StockWindow.setMinimumSize(QtCore.QSize(1300, 720))
        StockWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        StockWindow.setIconSize(QtCore.QSize(12, 12))
        self.centralwidget = QtWidgets.QWidget(StockWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(251, 193, 193, 158)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tableWidget.setFont(font)
        #self.tableWidget.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tableWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("background-color:rgb(238, 238, 236)")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setStyleSheet("background-image: url(./imagenes/sophia_trans.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-color:rgb(255, 255, 255)")
        self.tableWidget.horizontalHeader().setStyleSheet("background-color: rgb(255,255,255)")
        self.tableWidget.verticalHeader().setStyleSheet("background-image: url(./imagenes/headerv.png)")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        check_box = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.horizontalHeader().setDefaultSectionSize(252)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_6.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit.setStyleSheet("background-color:rgb(255,255,255)")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.searchbutton = QtWidgets.QPushButton(self.centralwidget)
        self.searchbutton.setMinimumSize(QtCore.QSize(200, 60))
        self.searchbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchbutton.setStyleSheet("background-color:rgb(117, 80, 123)")
        self.searchbutton.setObjectName("searchbutton")
        self.horizontalLayout_5.addWidget(self.searchbutton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.one_to_storage = QtWidgets.QPushButton(self.centralwidget)
        self.one_to_storage.setMinimumSize(QtCore.QSize(231, 71))
        self.one_to_storage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.one_to_storage.setStyleSheet("background-color:rgb(117, 80, 123)")
        self.one_to_storage.setIconSize(QtCore.QSize(50, 16))
        self.one_to_storage.setObjectName("one_to_storage")
        self.horizontalLayout.addWidget(self.one_to_storage)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.n_increase_stock = QtWidgets.QSpinBox(self.centralwidget)
        self.n_increase_stock.setMinimumSize(QtCore.QSize(0, 40))
        self.n_increase_stock.setStyleSheet("background-color:rgba(173, 127, 168, 191)")
        self.n_increase_stock.setObjectName("n_increase_stock")
        self.horizontalLayout.addWidget(self.n_increase_stock)
        self.increase_stock = QtWidgets.QPushButton(self.centralwidget)
        self.increase_stock.setMinimumSize(QtCore.QSize(0, 40))
        self.increase_stock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.increase_stock.setStyleSheet("background-color:rgb(117, 80, 123)")
        self.increase_stock.setObjectName("increase_stock")
        self.horizontalLayout.addWidget(self.increase_stock)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.one_to_front = QtWidgets.QPushButton(self.centralwidget)
        self.one_to_front.setMinimumSize(QtCore.QSize(231, 71))
        self.one_to_front.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.one_to_front.setStyleSheet("background-color:rgb(117, 80, 123)")
        self.one_to_front.setObjectName("one_to_front")
        self.horizontalLayout.addWidget(self.one_to_front)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_3.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.n_to_storage = QtWidgets.QPushButton(self.centralwidget)
        self.n_to_storage.setMinimumSize(QtCore.QSize(0, 50))
        self.n_to_storage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n_to_storage.setStyleSheet("background-color:rgb(117, 80, 123)")
        self.n_to_storage.setObjectName("n_to_storage")
        self.verticalLayout.addWidget(self.n_to_storage)
        self.n_to_storage_num = QtWidgets.QSpinBox(self.centralwidget)
        self.n_to_storage_num.setMinimumSize(QtCore.QSize(236, 0))
        self.n_to_storage_num.setStyleSheet("background-color:rgba(173, 127, 168, 191)")
        self.n_to_storage_num.setObjectName("n_to_storage_num")
        self.verticalLayout.addWidget(self.n_to_storage_num)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.n_decrease_stock = QtWidgets.QSpinBox(self.centralwidget)
        self.n_decrease_stock.setMinimumSize(QtCore.QSize(0, 40))
        self.n_decrease_stock.setStyleSheet("background-color:rgba(173, 127, 168, 191)")
        self.n_decrease_stock.setObjectName("n_decrease_stock")
        self.horizontalLayout_2.addWidget(self.n_decrease_stock)
        self.Decrease_stock = QtWidgets.QPushButton(self.centralwidget)
        self.Decrease_stock.setMinimumSize(QtCore.QSize(0, 40))
        self.Decrease_stock.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Decrease_stock.setStyleSheet("background-color:rgb(117, 80, 123)")
        self.Decrease_stock.setObjectName("Decrease_stock")
        self.horizontalLayout_2.addWidget(self.Decrease_stock)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.n_to_front = QtWidgets.QPushButton(self.centralwidget)
        self.n_to_front.setMinimumSize(QtCore.QSize(236, 50))
        self.n_to_front.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n_to_front.setStyleSheet("background-color:rgb(117, 80, 123)")
        self.n_to_front.setObjectName("n_to_front")
        self.verticalLayout_2.addWidget(self.n_to_front)
        self.n_to_front_num = QtWidgets.QSpinBox(self.centralwidget)
        self.n_to_front_num.setMinimumSize(QtCore.QSize(0, 25))
        self.n_to_front_num.setStyleSheet("background-color:rgba(173, 127, 168, 191)")
        self.n_to_front_num.setObjectName("n_to_front_num")
        self.verticalLayout_2.addWidget(self.n_to_front_num)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(388, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.close_stock_window = QtWidgets.QPushButton(self.centralwidget)
        self.close_stock_window.setMinimumSize(QtCore.QSize(200, 50))
        self.close_stock_window.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_stock_window.setStyleSheet("background-color:rgb(117, 80, 123)")
        self.close_stock_window.setObjectName("close_stock_window")
        self.horizontalLayout_4.addWidget(self.close_stock_window)
        spacerItem14 = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        StockWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StockWindow)
        QtCore.QMetaObject.connectSlotsByName(StockWindow)

        #Activation for searchbutton. Search products.
        self.searchbutton.clicked.connect(self.searchbutton_clicked)
        
        #Activation for increase_stock
        self.increase_stock.clicked.connect(self.increase_stock_clicked)


    #Increase stock, depending on QSpingBox.
    def increase_stock_clicked(self):
        print(self.n_increase_stock.value())


    def get_checked_products(self):
        if row_count == 0:
            pass
        else:
            for i in range(self.row_count):
                print(self.tableWidget.rowCount())
                if self.tableWidget.cellWidget(i,4).isChecked():
                    self.checked_list.append([i,4])
            print(self.checked_list)

        #pass

    # Populate table with the product given.
    def searchbutton_clicked(self):
        print(self.lineEdit.text())
        product = show_product(self.lineEdit.text(),1)
        self.tableWidget.setRowCount(0)
        for row_number, row_data, in enumerate(product):
            self.row_count = self.row_count + 1 
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                if type(data) == float:
                    data = int(data)
                item = QTableWidgetItem(str(data))
                item.setTextAlignment(Qt.AlignCenter)
                self.tableWidget.setItem(row_number,column_number,item)
                if column_number == 3:
                    #Create CheckBox 
                    check_box_item = QTableWidgetItem()
                    check_box_item.setCheckState(Qt.Unchecked)
                    check_box_item.setText("Seleccionar")
                    check_box_item.setTextAlignment(Qt.AlignLeft)
                    # Add CheckBox in the last column in every row
                    self.tableWidget.setItem(row_number,column_number+1,check_box_item)

    def retranslateUi(self, StockWindow):
        _translate = QtCore.QCoreApplication.translate
        StockWindow.setWindowTitle(_translate("StockWindow", "Stock"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("StockWindow", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("StockWindow", "Stock en deposito"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("StockWindow", "Stock en mostrador"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("StockWindow", "Codigo de Barras"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("StockWindow", "Modificar"))
        self.searchbutton.setText(_translate("StockWindow", "Buscar"))
        self.one_to_storage.setText(_translate("StockWindow", "Subir un solo producto al deposito"))
        self.increase_stock.setText(_translate("StockWindow", "Aumentar stock"))
        self.one_to_front.setText(_translate("StockWindow", "Bajar un solo producto del deposito"))
        self.n_to_storage.setText(_translate("StockWindow", "Subir al deposito:"))
        self.Decrease_stock.setText(_translate("StockWindow", "Disminuir sotck"))
        self.n_to_front.setText(_translate("StockWindow", "Bajar del deposito:"))
        self.close_stock_window.setText(_translate("StockWindow", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StockWindow = QtWidgets.QMainWindow()
    ui = Ui_StockWindow()
    ui.setupUi(StockWindow)
    StockWindow.show()
    sys.exit(app.exec_())
